# Generated by Django 5.1.1 on 2024-09-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Contacto', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=50)),
                ('Estilo', models.CharField(max_length=50)),
                ('Integrantes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Barandpubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Contacto', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=50)),
                ('Estilo', models.CharField(max_length=50)),
                ('dir', models.CharField(max_length=50)),
                ('Sonidopropio', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Musicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('instrumento', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('dni', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salasensayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Contacto', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=50)),
                ('Estilo', models.CharField(max_length=50)),
                ('dir', models.CharField(max_length=50)),
                ('cantsalas', models.IntegerField()),
            ],
        ),
    ]
